<a href="https://colab.research.google.com/github/nk8410j/comp1804/blob/master/IrisClassifier123.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt


from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score 
from sklearn.metrics import confusion_matrix




In [34]:
columns = ['sepal_length', ' sepal_width', 'petal_length', 'petal_width', 'class']
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', names=columns)
df.head()

sepal_length   sepal_width  petal_length  petal_width        class
0           5.1           3.5           1.4          0.2  Iris-setosa
1           4.9           3.0           1.4          0.2  Iris-setosa
2           4.7           3.2           1.3          0.2  Iris-setosa
3           4.6           3.1           1.5          0.2  Iris-setosa
4           5.0           3.6           1.4          0.2  Iris-setosa

In [35]:
df['class'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [36]:
df['class_encod'] = df['class'].apply(lambda x: 0 if x == 'Iris-setosa' else 1 if x == 'Iris-versicolor' else 2)
df['class_encod'].unique()

array([0, 1, 2])

In [37]:
y = df[['class_encod']] 
X = df.iloc[:, 0:4] 
df.head()

sepal_length   sepal_width  ...        class  class_encod
0           5.1           3.5  ...  Iris-setosa            0
1           4.9           3.0  ...  Iris-setosa            0
2           4.7           3.2  ...  Iris-setosa            0
3           4.6           3.1  ...  Iris-setosa            0
4           5.0           3.6  ...  Iris-setosa            0

[5 rows x 6 columns]

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,
                                                    random_state=0, stratify=y)

In [39]:

model1 = KNeighborsClassifier()
model1.fit(X_train, np.ravel(y_train))
model1.predict(X_test)

model2 = DecisionTreeClassifier()
model2.fit(X_train, np.ravel(y_train))
model2.predict(X_test)

model3 = LogisticRegression()
model3.fit(X_train, np.ravel(y_train))
model3.predict(X_test)

model4 = LinearDiscriminantAnalysis()
model4.fit(X_train, np.ravel(y_train))
model4.predict(X_test)

model5 = GaussianNB()
model5.fit(X_train, np.ravel(y_train))
model5.predict(X_test)

model6 = SVC()
model6.fit(X_train, np.ravel(y_train))
model6.predict(X_test)

array([2, 2, 0, 0, 1, 0, 1, 2, 0, 1, 0, 2, 0, 2, 1, 2, 1, 1, 1, 0, 1, 2,
       0, 1, 2, 2, 2, 2, 1, 2, 1, 0, 0, 1, 1, 2, 1, 0, 0, 1, 0, 2, 0, 0,
       2])

In [65]:

print ("Accuracy score of KNeighbors Classifier:", model1.score(X_test, y_test))

Accuracy score of KNeighbors Classifier: 1.0


In [66]:
print ("Confusion Matrix of KNeighbors Classifier:")
confusion_matrix(y_test, model1.predict(X_test))


Confusion Matrix of KNeighbors Classifier:


array([[15,  0,  0],
       [ 0, 15,  0],
       [ 0,  0, 15]])

In [64]:
print ("Accuracy score of Decision Tree Classifier:", model2.score(X_test, y_test))

Accuracy score of Decision Tree Classifier: 0.9555555555555556


In [63]:
 print ("Confusion Matrix of Decision Tree Classifier:")
confusion_matrix(y_test, model2.predict(X_test))

Confusion Matrix of Decision Tree Classifier:


array([[15,  0,  0],
       [ 0, 15,  0],
       [ 0,  2, 13]])

In [60]:
print ("Accuracy score of Logistic Regression:", model3.score(X_test, y_test))


Accuracy score of Logistic Regression: 1.0


In [59]:
print ("Confusion Matrix of Logistic Regression:")
confusion_matrix(y_test, model3.predict(X_test))


Confusion Matrix of Logistic Regression:


array([[15,  0,  0],
       [ 0, 15,  0],
       [ 0,  0, 15]])

In [58]:
print ("Accuracy score of  Linear Discriminant Analysis:", model4.score(X_test, y_test))

Accuracy score of  Linear Discriminant Analysis: 1.0


In [57]:
print ("Confusion Matrix of Linear Discriminant Analysis:")
confusion_matrix(y_test, model4.predict(X_test))

Confusion Matrix of Linear Discriminant Analysis:


array([[15,  0,  0],
       [ 0, 15,  0],
       [ 0,  0, 15]])

In [68]:
print ("Accuracy score of GaussianNB:", model5.score(X_test, y_test))

Accuracy score of GaussianNB: 0.9777777777777777


In [69]:
print ("Confusion Matrix of GaussianNB:")
confusion_matrix(y_test, model5.predict(X_test))

Confusion Matrix of GaussianNB:


array([[15,  0,  0],
       [ 0, 15,  0],
       [ 0,  1, 14]])

In [70]:
print ("Accuracy score of SVC:", model6.score(X_test, y_test))

Accuracy score of SVC: 1.0


In [71]:
print ("Confusion Matrix of SVC:")
confusion_matrix(y_test, model6.predict(X_test))

Confusion Matrix of SVC:


array([[15,  0,  0],
       [ 0, 15,  0],
       [ 0,  0, 15]])

In [0]:
from sklearn.model_selection import cross_val_score

In [76]:
knn = KNeighborsClassifier()
scores = cross_val_score(knn, X, y.values.ravel(), cv=10, scoring='accuracy').mean()
print(scores)

0.9666666666666668


In [77]:
logreg = LogisticRegression(penalty="l2", max_iter=1000)
scores1 = cross_val_score(logreg, X, y.values.ravel(), cv=10, scoring='accuracy').mean()
print(scores1)

0.9733333333333334


In [78]:
DTC = DecisionTreeClassifier()
scores = cross_val_score(DTC, X, y.values.ravel(), cv=10, scoring='accuracy').mean()
print(scores)

0.9533333333333334


In [79]:
LDA = LinearDiscriminantAnalysis()
scores = cross_val_score(LDA, X, y.values.ravel(), cv=10, scoring='accuracy').mean()
print(scores)

0.9800000000000001


In [80]:
GNB = GaussianNB()
scores = cross_val_score(GNB, X, y.values.ravel(), cv=10, scoring='accuracy').mean()
print(scores)

0.9533333333333334


In [81]:
SVC = SVC()
scores = cross_val_score(SVC, X, y.values.ravel(), cv=10, scoring='accuracy').mean()
print(scores)

0.9733333333333334
